# vim:fileencoding=utf-8

# Font Configuration
font_family      family="InputMonoEx Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size        13.0

# Window
remember_window_size   yes
initial_window_width   1200
initial_window_height  800

# Cursor
cursor_shape     beam
cursor_beam_thickness 1.5

# Scrollback
scrollback_lines 10000

# Bell
enable_audio_bell yes

# Tabs
tab_bar_edge     top
tab_bar_style    powerline

# Theme
include current-theme.conf